version: "3.1"

# Env vars provided in a .env file

services:
  # The Postgres db
  journal-db:
    image: postgres
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: main
    ports:
      - 5432:5432
