version: "3.1"

# Env vars provided in a root level .env file

services:
  # The Postgres db (a test db is setup as-needed by npm test)
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "db"
    ports:
      - 5432:5432
