version: "3.1"

# Env vars provided in a .env file

services:
  # The Postgres db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "db"
    ports:
      - 5432:5432
